# Generated by Django 4.1.2 on 2024-11-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criptomonedas',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('simbolo', models.CharField(db_column='Símbolo', max_length=10)),
                ('precio_usd_field', models.CharField(db_column='Precio (USD)', max_length=50)),
                ('vol_24h_field', models.CharField(blank=True, db_column='Vol. (24h)', max_length=50, null=True)),
                ('vol_total', models.CharField(blank=True, db_column='Vol. Total', max_length=50, null=True)),
                ('var_24h_field', models.CharField(blank=True, db_column='Var. (24h)', max_length=50, null=True)),
                ('var_7d_field', models.CharField(blank=True, db_column='Var. (7d)', max_length=50, null=True)),
                ('cap_mercado', models.CharField(blank=True, db_column='Cap. mercado', max_length=50, null=True)),
            ],
            options={
                'db_table': 'criptomonedas',
                'managed': False,
            },
        ),
    ]
